
##############################################
### Rstate_compile ###
##############################################

### META ###
# HHakkinen
# Complete Date: 01/07/2021
# University of Exeter
# Code repo used to support:
#   "Plant naturalisations are constrained by temperature but released by precipitation"
# 
# This compiles a summary of results from "plant_PCA_expand.R"
# When processing many species, we may want to run code in blocks or examine subsections of results
# In these cases "plant_PCA_expand.R" will save R states, one per species, which can be compiled later by this script
# This script loads R states generated by "plant_PCA_expand.R",  calculates and compiles results and saves output as both a .txt and a .tif


### ###



rm(list=ls())


###################################
#set paths and variables
##################################


#set the name of the variable set. Has to be the same as "folOut" variable on line 85 of plant_PCA_expand
#we use this name to keep track of output and results
varSet<-"3Var"

#set to path of local repo
repoPath<-"DIRECTORY_HERE"
#set directory, will compile results in this folder (note that default is plant_PCA_exp, adjust if necessary)
setwd(paste0(repoPath, "/IntermediateOutput/plant_PCA_exp/",varSet,"/rstates_center/"))

#set the name of the output summary statistics file
csvfile4<- paste0("../../../Rstate_compile/",varSet,"_plant_D_shiftvalues_zcor_center.txt")

#set the name of the output raster brick file
rasfile5<- paste0("../../../Rstate_compile/",varSet,"_composite_rasterEXP_zcor.tif",sep="")



###################################
#load, compile and save key statistics
##################################
#compile all the summary statistics produced by "plant_PCA_expand.R" and save one massive table


#load all files that are successful
yooo<-list.files(pattern="*_nicheshift.R")
#load any failed files
fail<-list.files(path="flaws",pattern="*_nicheshift.R")

#check if there is any crossover, remove any failed files (there shouldn't be any but worth checking)
yooo<-yooo[!(yooo %in% fail)]


#load the first file as a template
load(yooo[1])
D.df_total<-D.df

#load each state in turn and append to the result "stack"
for (n in yooo){
  print(n)
  load(n)
  i<-D.df

  #print(i[1])
  #check for error state, remove if so
  if(i[1] != "" & i[1] != "not enough known occurrences to calculate niche"){D.df_total<-rbind(D.df_total,i)}
}


#remove (duplicated first entry)
D.df_total<-D.df_total[-c(1),]
#check list is complete
names(D.df_total)
head(D.df_total)


#write results table
write.table(D.df_total, csvfile4, row.names = F, sep = "\t")

#double check that table is formed properly
D.df_convert<-read.table(csvfile4,row.names=NULL)

#weird bug I sometimes get where species names are seperated
#should fix, but currently fudged
D.df_convert$species.name<-paste(D.df_convert$row.names,D.df_convert$species.name)
D.df_convert$row.names<-NULL

#write again but with correct names
write.table(D.df_convert, csvfile4, row.names = F, sep = "\t")


###################################
#load, compile and save raster bricks of niches
##################################
#compile all the raster bricks produced by "plant_PCA_expand.R" and save one massive brick

library(raster)
library(RColorBrewer)

#set to raster output
setwd(paste0(repoPath, "/IntermediateOutput/plant_PCA_exp/",varSet,"/shift_PCArasters/"))

#function to remove NA values from raster bricks
remove_na<-function(x){
  #print(x)
  #print(class(x))
  #x$expansion[is.na(x$expansion)] <- 0
  #x$unfilling[is.na(x$unfilling) m] <- 0
  #x$natur_occ[is.na(x$natur_occ)] <- 0
  x[is.na(x)]<-0
  return(x)
}

#load all bricks of interest
brick_list<-list.files(pattern="*_PCAraster.tif")

#load first brick as a template
raster_pile<-brick(brick_list[1])
#remove NA values to allow addition
raster_pile<-remove_na(raster_pile)


#load each brick and add to existing template stack
for (i in 2:length(brick_list)){
  print(i)
  raster_new<-brick(brick_list[i])
  raster_new<-remove_na(raster_new)
  
  raster_pile<-Reduce("+",list(raster_pile,raster_new))
  
  #close file, to avoid memory pileup
  removeTmpFiles(h=0)
}

#check names
names(raster_pile)

#do some basic plots to make sure it makes sense
cols <- rev(brewer.pal(11,"Spectral"))
raster_plot<-raster_pile
raster_plot[raster_plot==0]<-NA
plot(raster_plot$layer,col=cols)


#save the output
writeRaster(raster_pile, rasfile5, options= c("COMPRESSION=LZW","INTERLEAVE=PIXEL"), overwrite=TRUE)

#check you can load the brick and it looks ok!
raster_check<-raster(rasfile5);names(raster_check)<-"layer"





